### ISSUE TITLE
Convert uploadFile to new api

### ISSUE THREAD

**Issue by kalisp** [ynput/ayon-slack#16]
![image](https://github.com/ynput/ayon-slack/assets/4457962/b1864c28-f98d-4e33-90a7-d38ae7b39341)

**Comment by BigRoy** [comment]
I believe this issue is currently affecting us already.

```
WARNING: Error happened: method_deprecated
Traceback (most recent call last):
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\addons\slack_1.1.1\ayon_slack\plugins\publish\integrate_slack_api.py", line 343, in send_message
    response = self.client.files_upload(
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\slack_sdk\web\client.py", line 3603, in files_upload
    return self.api_call("files.upload", files={"file": file}, data=kwargs)
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\slack_sdk\web\base_client.py", line 157, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\slack_sdk\web\base_client.py", line 188, in _sync_send
    return self._urllib_api_call(
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\slack_sdk\web\base_client.py", line 319, in _urllib_api_call
    ).validate()
  File "C:\Users\Zjie\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\slack_sdk\web\slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://slack.com/api/files.upload)
The server responded with: {'ok': False, 'error': 'method_deprecated'}
```

**Comment by kalisp** [comment]
Resolved by https://github.com/ynput/ayon-slack/pull/21
